### ISSUE TITLE
Investigate how to deploy Neo4J on a docker container

### ISSUE THREAD

**Issue by razine-bensari** [DPigeon/Money-Tree#103]
As a user, I want to access my personal data on the app so that I can see my information properly.

When deploying to the 2 environments, we need to find a way to interact with the database. To achieve that, we must investigate a good strategy to persist our database data in production. On the other hand, the UAT environment can have test data and can be deleted at any time since it is a "test" environment. With the current CD pipeline script, a good solution must be investigated for both environments.

**Acceptance of Criteria:**

- [x] Figure out if we can simply incorporate a docker container for the neo4j db within the pipeline.

- [x] Figure out if when we do `docker image prune` it does not remove the db data.

- [x] Figure out if when we do `docker system prune` it does not remove the db data.

- [x] Figure out if when we stop a container and redeploy, or rebuild an image, the db data is not removed.

**Comment by DPigeon** [comment]
@Alessandro100 Razine and I had a quick meeting yesterday about how we could persist our database. I think that this should be investigated for next sprint. What are your thoughts ?

**Comment by Alessandro100** [comment]
I think it would be a good idea to investigate this. I know it is possible:
https://www.digitalocean.com/community/tutorials/how-to-install-neo4j-on-an-ubuntu-vps

In this story I would include investigating if its possible, and if it is, to integrate this. Let me know if you would like to split up the investigation / implementation in 2 different stories

**Comment by wltrf** [comment]
**Proposed solution:**
Use docker-compose to run and configure services (such as neo4j db) and make the application resilient to db connection failures

**Some context:**
A dockerfile contains information on how to build an image for individual services
https://docs.docker.com/engine/reference/builder/

Compose is a tool for defining and running multi-container Docker applications. With Compose, you use a YAML file to configure your application's services. Then, with a single command, you create and start all the services from your configuration.
https://docs.docker.com/compose/compose-file/

**Explanation:**
The proposed solution is to create a dockerfile to build the springboot application image only. Then a docker compose file will contain the image for neo4j db and the image for the springboot application. Both images can then be run with a single command using docker-compose up.

Now, @razine-bensari raised an issue quoted below:
`If we define the services in docker-compose file, in order for the springboot app to load correctly, it will try to establish a connection with the DB. If it cannot establish the connection, the app deployemnt will fail.
In docker-compose we have no control to define which service will be deployed before the other (only which will be built before the other).
We can use the depend-on  attribute in docker file but that may not work.`

The reason we cannot use the depend-on attribute is because it will only define the order of start of the services, but wont wait until the service in question is ready/completely started.

The solution to this problem, is to make the application resilient to connection errors, instead of the services blindly assuming that some preconditions are met. Unfortunately, springboot doesn't support this by default. There is an open issue about it (https://github.com/spring-projects/spring-boot/issues/4779) where some solutions are proposed.
One of these solutions (https://github.com/spring-projects/spring-boot/issues/4779#issuecomment-305482782) propose to use Spring Retry (walkthrough here: https://www.baeldung.com/spring-retry). Will need to test if it works with our setup.

**Comment by razine-bensari** [comment]
Super nice search! I didnt know about the open issue in springboot!!!

**Comment by wltrf** [comment]
Another piece of information that I found interesting is from the [docker documentation](https://docs.docker.com/compose/startup-order/), it states the following:
>The problem of waiting for a database (for example) to be ready is really just a subset of a much larger problem of distributed systems. In production, your database could become unavailable or move hosts at any time. Your application needs to be resilient to these types of failures.
>To handle this, design your application to attempt to re-establish a connection to the database after a failure. If the application retries the connection, it can eventually connect to the database.
>The best solution is to perform this check in your application code, both at startup and whenever a connection is lost for any reason.`

Insightful in terms of design

**Comment by wltrf** [comment]
**Better Solution:**
Configure a restart policy in the config for the docker-compose container. More specifically, on-failure flag which will restart the springboot application on failure, forever or until a condition is met. This would also take care of other failures that could happen in production and would restart the app.
https://docs.docker.com/config/containers/start-containers-automatically/
https://docs.docker.com/compose/production/

This is both simpler and probably more appropriate for our case as it reduces complexity of the datasource connection and doesn't require an extra dependency.

**Comment by wltrf** [comment]
To answer the question of **data resilience** whenever we restart the application, it is achieved by connecting the docker environment of the neo4j application to a persistent data folder on the host. This is done using the `--volume` flag similar to the following:
`--volume=$HOME/neo4j/data:/data`
We can either have the same folder configuration for both UAT and PROD, or we can specify different config files for each with different folders.

**Comment by DPigeon** [comment]
Nice research! 
Also about the last post: I think it is better to have different config files for each database so that we have a "test" db/volume on uat and a "prod" db/volume on prod.

**Comment by wltrf** [comment]
The above solution works, but I looked at this again and found a simpler solution. There is a maven dependency that we can use for neo4j and we can secify a config file `neo4j.conf`. This config file can contain properties like `dbms.directories.neo4j_home` which specify where the data is stored, and we could link that to outside the image environment so that we persist data and logs.
Actions to implement this are:

1. Add the following dependency:
`  <dependency>
   <groupId>org.neo4j</groupId>
   <artifactId>neo4j</artifactId>
   <version>4.1.3</version>
  </dependency>`

2. Create a neo4j.conf file with the following content:
`dbms.directories.neo4j_home = <path>`

3. When running the docker image, expose the above <path> by using `--volume` flag
