### ISSUE TITLE
Investigate Alpaca web hooks for the backend

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#158]
As a developer I would like to implement the Alpaca web hook looking for trade updates so I can work with this in future stories

**Acceptance Criteria**
- We understand how to implement the Alpaca webhook into our project
- The web hook can detect if a trade has been fulfilled and can return key information

**Comment by DPigeon** [comment]
So I started investigating this. The web hooks can be integrated with Alpaca using streamUpdates. I thought about two ways that we could do this. Here are some sequence diagrams I've made to understand the flow better.

- With backend
![AlpacaWebHooksWithBackend](https://user-images.githubusercontent.com/37888675/99975123-d601e400-2d6f-11eb-80f5-5affa3c35a13.png)

- Without backend (only client)
![AlpacaWebHooksWithClient](https://user-images.githubusercontent.com/37888675/99975137-da2e0180-2d6f-11eb-88c6-2e022f06fdee.png)

As you can see, I think it would be better if we'd do this on the client side with Angular as it would remove an extra layer that we need to have. 
Indeed, to constantly listen to trade updates, we need to use websockets. Using the backend in this setup would make us create a websocket server on the backend that listens to trade_updates on AlpacaAPI. Meanwhile, the client would need to have a websocket client (per user) that listens to updates sent from the websocket backend server. 

On the other side, if we do it without the backend, then it removes the websocket backend server and we can simply listen to trade_updates from AlpacaAPI on the client with a websocket client. This solution is simpler, but it may be a bad solution for security and CORS cross-origin problems.

Let me know what you think.

**Comment by Alessandro100** [comment]
I do agree that removing the backend would be simpler but it comes at a cost. Let's say the user receives an update saying that their order is fulfilled, we would need to update the backend saying
1. This transaction is complete (create / update the transaction node)
2. Update their score (if it's a sell)
This information needs to be updated in the backend or else other users would never know what transactions this user did. 
I think having the backend coordinate this is needed. From the backend, we can host a webserver that the frontend client will connect to. https://stackoverflow.com/questions/22367223/sending-message-to-specific-user-on-spring-websocket

**Comment by DPigeon** [comment]
Makes sense! Then we need the backend.

**Comment by Alessandro100** [comment]
Looks good, but once the client is connected to the WebSocket, they wont need to call 'getTradeUpdates()'. Unless getTradeUpdates is the call that connects the user to the backend WebSocket?

**Comment by DPigeon** [comment]
Yeah getTradeUpdates would be a function on Angular calling ws.receive() or something. It's just an idea for now but as soon as you setup the websocket client on the frontend, it may be different.
![AlpacaWebHooks](https://user-images.githubusercontent.com/37888675/99985726-4f9fcf00-2d7c-11eb-9104-5ab07306e12d.png)

**Comment by DPigeon** [comment]
I have found interesting documentation on how websockets works with STOMP on spring:
https://www.baeldung.com/websockets-spring
https://www.baeldung.com/spring-websockets-send-message-to-user
https://www.baeldung.com/spring-websockets-sendtouser

For integration tests:
https://medium.com/@MelvinBlokhuijzen/spring-websocket-endpoints-integration-testing-180357b4f24c
However, the config setup for the tests will be different with Spock. 

The sequence diagram above was made.

I made a spike branch to play around with the websocket protocol and to see how we can integrate the Alpaca trade update streams. I think that this story should be separated into 2 stories for
- Investigate/Spike (this one)
- Implementation/Tests (properly setting up the clientOutBound trade stream updates, setup the websockets config tests with Spock properly, integration tests with websockets etc)

What do you think? Because I saw that as an acceptance criteria we want it to be implemented, but it is a spike/research story.
