### ISSUE TITLE
Investigate CORS/ActuatorHealth Issues on the UAT / PROD environment

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#178]
As a developer I would not like to have any CORS issues in the UAT / PROD environment so I can see actual data

**Acceptance Criteria**
- There are no CORS bugs in the UAT / PROD env

**Comment by DPigeon** [comment]
@razine-bensari I investigated a bit on this and it seems like CORS is working fine now (we don't get any CORS error if we go to http://dev.money-tree.tech/stock-detail/ac and look at the browser console in dev options). Indeed, we're getting a CONNECTION_REFUSED because we did not setup any Neo4j database on any environments in the VMs except for the testing database. 

So we'll have to do that.

**Comment by DPigeon** [comment]
One solution I see after reading [this](https://docs.docker.com/compose/networking/): 
- Use docker compose on the VMs with backend and neo4j linked together
- Inject the production profile when deploying on uat/prod
- Then in the prod properties we can use IMAGE_NAME://SERVICE_NAME:7687 in the prod properties like
```
spring.data.neo4j.uri=neo4j://neo4jdb:7687 
```
- Now our backend container will be able to talk to our neo4j container correctly since they will be on the same network using the proper container IP (neo4jdb refers to the docker IP of the service container). 

The reason we should use docker compose is that without it, we'll have to put the specific docker IP of the neo4j container that is on the same network. That would be something like 172.10.0.2 for example (starting with 172). The properties would become
 ```
spring.data.neo4j.uri=bolt://172.10.0.2:7687
```
And that can become messy especially if we use uat and prod with the same prod-property file because both neo4j containers on the uat and prod VMs may resolve to different IPs. Using docker compose helps us "hide" the IP of the container and call it with its service name instead.

I am still investigating. I know this is far from being a CORS problem so we may change the title of this issue accordingly.

**Comment by razine-bensari** [comment]
I see, thks for the research, indeed, using docker compose will create an internal network for all services within the docker-compose file. I guess we can do that within that ticket
