### ISSUE TITLE
Cannot create new user or login with an existing user on https://dev.money-tree.tech/

### ISSUE THREAD

**Issue by EspressoCode** [DPigeon/Money-Tree#296]
**Describe the bug**
When trying to create new user or login with an existing user I get errors.

**To Reproduce**
1. Go to https://dev.money-tree.tech/
2. Try to create a new user or login with an existing one.
3. Press F12 to see errors on Chrome Developer tool.

**Expected behavior**
User should be able to login / new user has to be created without problems.

**Screenshots**
for when creating a user:
![create new user](https://user-images.githubusercontent.com/33170291/108112785-6ee08c80-704b-11eb-933d-6131b3f4409a.PNG)

for when logging in with an existing user:
![login](https://user-images.githubusercontent.com/33170291/108112820-7bfd7b80-704b-11eb-8ee8-34f5d8daf1bf.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 88.0.4324.150 (Official Build) (64-bit)

**Additional context**
I also tried it on my phone and got the same error.

**Comment by DPigeon** [comment]
Just pulled the logs from the frontend container and this is what we're seeing:
```
[error] 6#6: *8408 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream
```

Something to do with nginx. Its weird that this error occurs now as the SSL was working before. Seems that it is broken now. I'll have to investigate when I'll have the chance.

**Comment by DPigeon** [comment]
Update: I am currently working on this bug #300 and it seems like it relates to this one as well. Let's see if it fixes it otherwise I will investigate this one afterwards more in-depth.

**Comment by wltrf** [comment]
I think I know the problem: looks like it comes from pr #288. That pr changed the default maven profile from dev to local. The way it works when specifying a profile is the following: 1. use the default profile, 2. override any properties of the default with values from the specified profile. 
Now the problem is that the local profile has an extra property that disables ssl, but the other profiles don't have that property to enable it. so by switching the default profile to be local, by default ssl is disabled.

**Comment by DPigeon** [comment]
> I think I know the problem: looks like it comes from pr #288. That pr changed the default maven profile from dev to local. The way it works when specifying a profile is the following: 1. use the default profile, 2. override any properties of the default with values from the specified profile.
> Now the problem is that the local profile has an extra property that disables ssl, but the other profiles don't have that property to enable it. so by switching the default profile to be local, by default ssl is disabled.

Good catch! I didn't see that myself while implementing the PR. Thanks!

**Comment by DPigeon** [comment]
@wltrf just tried to create an account on UAT but got the same error in the logs:
[error] 6#6: *8408 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream
```

We'll have to investigate more. Seems like a nginx issue.

**Comment by wltrf** [comment]
Figured it out.

**problem**
For some reason the -Dspring.profiles.active argument doesn't work. 
Since the default profile used to be dev, we didn't notice that. And since we don't deploy to master until the end of the release, we didn't notice it there either until now.
Therefore it caused the following issues:
1. prod serves the dev certificate (since last time we deployed to prod, dev was the default profile)
2. uat uses the local profile which has ssl disabled (since now the default profile is local)

**solution**
Specifying the env variable SPRING_PROFILES_ACTIVE in each vm with their respective values fixed the issue.
