### ISSUE TITLE
Transactions and owned stocks not updated when trade updates are happening 

### ISSUE THREAD

**Issue by EspressoCode** [DPigeon/Money-Tree#328]
**Describe the bug**
This bug is actually the result of merging a pr into dev while it was the weekend and the market was closed. When the market is closed, the application does not go through the listeners, where the problematic part was causing the errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the stock-detail page and try to make any transaction during the market opening time
2. You will get an error in the backend and the transaction will not be updated

**Expected behaviour**
The transaction has to be updated and stock should be added.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 88

**Additional context**
There is another bug related to the WebSocket and email sender which has to be addressed and I will create another ticket for that bug.

**Comment by DPigeon** [comment]
This Alpaca Market hours is very annoying. Let me know any updates and I`ll try to help via Slack. 

For the login/logout bug that we talked about in the meeting yesterday, I am very curious as to why it is not working properly. When user login, it should listen to streams. If it logs out, then it disconnects from them. So now you're saying that when a user logs in, it connects to them and when logs out it reconnects sending another email. 

Maybe we can change the design in the backend so that when a user connects to the streams, it checks and does the transaction stuff, sends email if needed etc, wait for 5 secs (Thread.Sleep like in the docs on AlpacaAPI Java) and then disconnect. So we wouldn't have to disconnect everytime we logout. It would disconnect every time we're done fetching the trade updates 5 secs after it has connected. I thought it this design at first but since the AlpacaSession was not implemented yet, the Thread.Sleep with disconnecting right away was giving me an Alpaca error saying I was not authenticated. Now, we are authenticated because we're using an oAuthToken with the AlpacaSession.

Let me know how it goes.

**Comment by EspressoCode** [comment]
Hi David, I am working on it right now, will keep you posted and reach out on Slack.

**Comment by DPigeon** [comment]
We probably won't be able to fix this by tomorrow (end of sprint). We can push this back to the next sprint.

**Comment by DPigeon** [comment]
@EspressoCode and I had a meeting today and we found [this](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/real-time/) info on Alpaca. For a basic plan, we cannot have more than 1 concurrent connection on the API. This is a blocker for this bug. More will be investigated later to see if we can find a workaround for this.
