### ISSUE TITLE
Create Class Diagram

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#63]
As a developer I would like a class diagram to better express the way this application will be built

**Acceptance Criteria**
- The class diagram will have to have at least 3 design patterns implements (must be justified)
- The class diagram must have sufficient detail for developers to get a good understanding of how to build the application
- The class diagram will be done with PlantUML
- Once finished the class diagram must be put in the 'Software Architecture' folder in google drive

**Comment by DPigeon** [comment]
If we`re now using Java as our backend, there exist a really good plugin for diagrams (class, sequencial) called [PlantUML](https://plantuml.com/class-diagram) on IntelliJ. It think it would be better than draw.io since it has very good reusability in the long run. Something to look into in the future.

**Comment by Alessandro100** [comment]
Hmm interesting, I have a few questions:
- Does this only work on IntelliJ?
- Do you think we would need to make 2 class diagrams for the frontend / backend?
- Is the class diagram autogenerated?

**Comment by DPigeon** [comment]
> Hmm interesting, I have a few questions:
> 
> * Does this only work on IntelliJ?
> * Do you think we would need to make 2 class diagrams for the frontend / backend?
> * Is the class diagram autogenerated?

- With Angular on the frontend, we can install the PlantUML extension on Visual Studio Code if we're planning on using that IDE.
- What we could do is create a folder on the root of our project called "diagrams" and have 2 subfolders inside called "frontend" & "backend" with all PlantUML (.puml) files inside. So yes I think making two class diagrams for both is what we need to do.
- Yes the diagram is generated in a window in the IDE when you write the code for it in your .puml file. It is extremely fast and better than draw.io since all text, arrows and colors are generated automatically depending on what you specify.

**Comment by DPigeon** [comment]
I have written a boilerplate example of a class diagram with the current class that we have on the **backend** base code using PlantUML. Refer to this [documentation](https://plantuml.com/class-diagram) for more information.

![example](https://user-images.githubusercontent.com/37888675/94393013-f9216600-0127-11eb-9967-8bd78c112b45.png)

**Comment by DPigeon** [comment]
I have worked on the class diagram on the **backend** by refactoring all packages into their own files with PlantUML. I have also added new classes to it to begin the creation of our real diagram (backend only).
