### ISSUE TITLE
Determine how to collect user performance information / logs effeciently

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#7]
As a developer I want to know the best way to collect performance information / user logs to know about and fix existing user issues

**Description of the requirement**
(Develop code in your app or use tools for collecting user
session recordings. If your software does not have UI, but it is a service, you can record service
logs using logging libraries, and perform Load and Stress testing. Analyze the collected data to
find ways to improve the UI experience or service performance)

**Question**
- Would this be as simple as implementing google analytics into our web app? - Alessandro
- Would implementing a tool like Lighthouse (https://developers.google.com/web/tools/lighthouse) be useful to our devOps cycle? - Alessandro

**Acceptance Criteria**
- A solution that will allow us to get user performance is proposed
- A solution that will allow us to get user logs efficiently is proposed
- Determine the key metrics that we need to log
- A suitable solution that fits our needs is proposed in the research folder in the google drive

**Comment by Alessandro100** [comment]
@wltrf can you document our discussion / what google analytics offers in our research document. It will be easier to pick up and revisit it Nov 9. After that I'll close the task

**Comment by wltrf** [comment]
On hold and moved to a release 2 milestone. no need to close.

**Comment by wltrf** [comment]
[Google Analytics](https://analytics.google.com) is a free solution that is very easy to implement, simply adding a js script and voilà! It allows to collect data about users such as number of users, unique users, where they come from (both physically and how they accessed the website e.g. typed directly, google search, ad campaign...), user activity, where they go, how long they stay on a page, what medium they use (browser, os, versions). It's great at what it does of collecting and displaying data about user sessions and gives a lot of insight. 
![Screenshot from 2020-11-27 10-03-53](https://user-images.githubusercontent.com/33789241/100462189-e24faf00-3097-11eb-967a-b7d5e58cdd5c.png)

![Screenshot from 2020-11-27 10-04-18](https://user-images.githubusercontent.com/33789241/100462216-eed40780-3097-11eb-9b16-8e48b8d89e55.png)

![Screenshot from 2020-11-27 10-04-44](https://user-images.githubusercontent.com/33789241/100462264-001d1400-3098-11eb-9456-560667e9beef.png)

![Screenshot from 2020-11-27 10-05-28](https://user-images.githubusercontent.com/33789241/100462328-1a56f200-3098-11eb-8b51-cf1f8a81a472.png)

**Comment by wltrf** [comment]
On a similar track is [Simple Analytics](https://simpleanalytics.com/). It offers less features than google mainly because it is more privacy oriented. An alternative if that's the route we want to go.
![Screenshot from 2020-11-27 10-10-41](https://user-images.githubusercontent.com/33789241/100462859-e16b4d00-3098-11eb-81f8-d3d3ef526a86.png)

**Comment by wltrf** [comment]
The above is more about real user sessions data collection. It gives us insight on users, but since we don't already have an existing user base, it won't give us much insight on the actual user experience and performance, so as suggested by @Alessandro100 , a tool like [Google Lighthouse](https://developers.google.com/web/tools/lighthouse) would be great. It runs locally either via npm or chrome devtools and gives performance metrics as well as other user experience oriented metrics such as accessibility and good practices. There's a nice video on their website liked above about how users are impatient and want faster loading times rather than a nice looing ui.
![Screenshot from 2020-11-27 10-13-52](https://user-images.githubusercontent.com/33789241/100463404-c3eab300-3099-11eb-88d2-b06ec2271978.png)

**Comment by wltrf** [comment]
https://web.dev/learn/ is a good ressource regardin lighthouse audits and other aspects of a good web app.
