### ISSUE TITLE
Setup DevOps Pipeline

### ISSUE THREAD

**Issue by Alessandro100** [DPigeon/Money-Tree#70]
As a developer I would like to setup the devops pipeline to be able to start coding features

**Acceptance Criteria**
- The devops pipeline is made to match the proposed solution in the 'research' document in google drive

**Comment by DPigeon** [comment]
I have added all workflows yaml files that we'll be working on with all their respective job name. You can see them at https://github.com/DPigeon/Money-Tree/actions. Be aware that you'll probably see errors as this is in development.

**Comment by DPigeon** [comment]
Note: multiple commits are on the devops branch. I will delete everything once all devops tests are done.

- The Integration job (Install, Lint, Tests & Package) is almost done. Just need the Package sub-job to do.
- SonarCloud may be the best option anymore since it requires us to create an organization (which limits us with space and GitHub Actions minutes). Therefore, I have found another solution: https://www.codacy.com/ which will have to be tested.
- The CD workflow still needs to be worked on.

**Comment by DPigeon** [comment]
Update: after playing around with Heroku, I am unable to deploy 2 web process (frontend and backend) at the same time. We would need to scale our dyno up to 2 for that and it is $25-$250 per month. This is a big limitation problem.

**Comment by DPigeon** [comment]
Update: 
- The CI pipeline has been reworked on by @abdulmansour . What is left to do is: run e2e tests, SonarCloud job & (optional, would be nice to have though) --> test coverage report uploaded to artifacts
- The CD pipeline has been completely redone with DigitalOcean. The frontend has been deployed [here](68.183.206.127) and backend [here](68.183.206.127:8080).

**Comment by wltrf** [comment]
Good to go on my end.

**Comment by wltrf** [comment]
Since we did a lot of test commits and this is very messy, we will squash all commits before merging into master. In order to keep some information about authors, we can add co-author information in the commit message. More info in the link below
https://docs.github.com/en/free-pro-team@latest/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors


Co-authored-by: wltrf <33789241+wltrf@users.noreply.github.com>
Co-authored-by: another-name <email(private email depending if email is pubic in settings)>

@DPigeon @abdulmansour

**Comment by DPigeon** [comment]
Yes indeed. I think we can write the co-author emails directly in the PR's squash merge commit. We should make sure it works before co-authoring in a PR.

**Comment by DPigeon** [comment]
This is the final workflow diagram for DevOps. Refer to it when needed. 
![DevOpsPipeline](https://user-images.githubusercontent.com/37888675/96377922-d26ab400-1156-11eb-9ac3-e3b3b812bf85.png)
